sudo: required
services: 
    - docker

before_install:
    - docker build -t tomdavis/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tomdavis/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-207167766304"
    bucker_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY